SET foreign_key_checks = 0;
drop table IF EXISTS wayangoutpostdb.class_sc_is_map;
drop table IF EXISTS wayangoutpostdb.class_sc_param;
drop table IF EXISTS wayangoutpostdb.intervention_selector;
drop table IF EXISTS wayangoutpostdb.is_param_base;
drop table IF EXISTS wayangoutpostdb.is_param_class;
drop table IF EXISTS wayangoutpostdb.is_param_sc;
drop table IF EXISTS wayangoutpostdb.is_param_value;
drop table IF EXISTS wayangoutpostdb.lc;
drop table IF EXISTS wayangoutpostdb.sc_class;
drop table IF EXISTS wayangoutpostdb.sc_is_map;
drop table IF EXISTS wayangoutpostdb.sc_param_map;
drop table IF EXISTS wayangoutpostdb.sc_param;
drop table IF EXISTS wayangoutpostdb.strategy_class;
drop table IF EXISTS wayangoutpostdb.strategy_component;
drop table IF EXISTS wayangoutpostdb.strategy;
SET foreign_key_checks = 1;
